services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Booking\Service\Booker:
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
            - '%bookingTax%'
            - '@App\Room\Repository\RoomRepository'
