services:
    core.message_bus.command_bus:
        class: 'App\Core\Infrastructure\MessageBus\MessageBus'
        arguments:
            $messageBus: "@command.bus"


    core.message_bus.query_bus:
        class: 'App\Core\Infrastructure\MessageBus\MessageBus'
        arguments:
            $messageBus: "@query.bus"

    App\Core\Infrastructure\MessageBus\CommandBus:
        arguments:
            - '@core.message_bus.command_bus'

    App\Core\Infrastructure\MessageBus\QueryBus:
        arguments:
            - '@core.message_bus.query_bus'




